# File: Dockerfile
FROM alpine:3.19

LABEL maintainer="moabukar" \
      description="A DevOps toolbox container with Terraform, Vault, Helm, kubectl, kind, Kafka CLI, AWS CLI, etc."

ARG TERRAFORM_VERSION="1.3.9"
ARG VAULT_VERSION="1.12.4"
ARG HELM_VERSION="3.11.2"
ARG KUBECTL_VERSION="v1.26.1"
ARG KIND_VERSION="v0.17.0"
ARG KAFKACTL_VERSION="2.10.1"
ARG TRAEFIK_VERSION="2.9.6"
ARG TASK_VERSION="3.19.0"

RUN apk update && \
    apk add --no-cache \
      bash \
      curl \
      wget \
      unzip \
      git \
      go \
      python3 \
      py3-pip \
      ca-certificates \
      tar

# Install AWS CLI (v2 is bigger, so let's keep v1 for smaller footprint)
RUN apk add --no-cache aws-cli

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O /tmp/terraform.zip \
  && unzip /tmp/terraform.zip -d /usr/local/bin \
  && chmod +x /usr/local/bin/terraform \
  && rm -rf /tmp/terraform.zip

# Install Vault
RUN wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip -O /tmp/vault.zip \
  && unzip /tmp/vault.zip -d /usr/local/bin \
  && chmod +x /usr/local/bin/vault \
  && rm -rf /tmp/vault.zip

# Install Helm
RUN wget https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz \
  && tar -xf /tmp/helm.tar.gz -C /tmp \
  && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
  && chmod +x /usr/local/bin/helm \
  && rm -rf /tmp/helm.tar.gz /tmp/linux-amd64

# Install kubectl
RUN wget https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl \
  && chmod +x /usr/local/bin/kubectl

# Install kind
RUN wget https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 -O /usr/local/bin/kind \
  && chmod +x /usr/local/bin/kind

# Install Traefik
RUN wget https://github.com/traefik/traefik/releases/download/v${TRAEFIK_VERSION}/traefik_v${TRAEFIK_VERSION}_linux_amd64.tar.gz -O /tmp/traefik.tar.gz \
  && tar -xf /tmp/traefik.tar.gz -C /tmp \
  && mv /tmp/traefik /usr/local/bin/traefik \
  && chmod +x /usr/local/bin/traefik \
  && rm -rf /tmp/traefik.tar.gz

# Install Task
RUN wget https://github.com/go-task/task/releases/download/v${TASK_VERSION}/task_linux_amd64.tar.gz -O /tmp/task.tar.gz \
  && tar -xf /tmp/task.tar.gz -C /usr/local/bin \
  && chmod +x /usr/local/bin/task \
  && rm /tmp/task.tar.gz

# Install kubectx / kubens
RUN wget https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx -O /usr/local/bin/kubectx \
  && wget https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens -O /usr/local/bin/kubens \
  && chmod +x /usr/local/bin/
